model:
  type: pointnet_dc
dataset: pointda
source: modelnet
target: scannet
aug: default
batch: 256
epoch: 10
lr: 0.0001
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: adam
  nesterov: True
  decay: 0.00005
  ema: 0