model:
  type: pointnet_dc
dataset: pointda
source: scannet
target: modelnet
aug: default
batch: 256
epoch: 50
lr: 0.001
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: adam
  nesterov: False
  decay: 0.00005
  ema: 0